export const BASE_FORM = {
  name: {
    type: 'string',
    value: '',
    error: false,
    required: true,
  },
  weight: {
    type: 'int',
    value: 0,
    error: false,
    required: true,
    minimum: 0,
    maximum: 65535,
  },
  description: {
    type: 'string',
    value: '',
    error: false,
    required: false,
  },
};

export const GLOBALS_FORM = {
  'ipv4-network': {
    type: 'string',
    value: '',
    error: false,
    required: true,
  },
  'ipv6-network': {
    type: 'string',
    value: '',
    error: false,
    required: true,
  },
};

export const UNIT_FORM = {
  name: {
    type: 'string',
    value: '',
    error: false,
    required: true,
  },
  location: {
    type: 'string',
    value: '',
    error: false,
    required: true,
  },
  timezone: {
    type: 'select',
    value: '',
    error: false,
    required: true,
    options: [
      'Midway Islands Time (UTC-11:00)',
      'Hawaii Standard Time (UTC-10:00)',
      'Pacific Standard Time (UTC-8:00)',
      'Mountain Standard Time (UTC-7:00)',
      'Central Standard Time (UTC-6:00)',
      'Eastern Standard Time (UTC-5:00)',
      'Puerto Rico and US Virgin Islands Time (UTC-4:00)',
      'Canada Newfoundland Time (UTC-3:30)',
      'Brazil Eastern Time (UTC-3:00)',
      'Central African Time (UTC-1:00)',
      'Universal Coordinated Time (UTC)',
      'European Central Time (UTC+1:00)',
      'Eastern European Time (UTC+2:00)',
      '(Arabic) Egypt Standard Time (UTC+2:00)',
      'Eastern African Time (UTC+3:00)',
      'Middle East Time (UTC+3:30)',
      'Near East Time (UTC+4:00)',
      'Pakistan Lahore Time (UTC+5:00)',
      'India Standard Time (UTC+5:30)',
      'Bangladesh Standard Time (UTC+6:00)',
      'Vietnam Standard Time (UTC+7:00)',
      'China Taiwan Time (UTC+8:00)',
      'Japan Standard Time (UTC+9:00)',
      'Australia Central Time (UTC+9:30)',
      'Australia Eastern Time (UTC+10:00)',
      'Solomon Standard Time (UTC+11:00)',
      'New Zealand Standard Time (UTC+12:00)',
    ],
  },
  'leds-active': {
    type: 'bool',
    value: true,
    error: false,
  },
  'random-password': {
    type: 'bool',
    value: false,
    error: false,
  },
  hostname: {
    type: 'string',
    value: '',
    error: false,
    required: false,
  },
};

export const METRICS_FORM = {
  statistics: {
    enabled: false,
    interval: {
      type: 'int',
      value: 60,
      error: false,
      required: true,
      minimum: 60,
      maximum: 1000,
      unit: 'seconds',
    },
    types: {
      value: [],
      type: 'multi',
      error: false,
      required: true,
      options: ['ssids', 'lldp', 'clients'],
    },
  },
  health: {
    enabled: false,
    interval: {
      type: 'int',
      value: 60,
      error: false,
      required: true,
      minimum: 60,
      maximum: 1000,
      unit: 'seconds',
    },
  },
  'wifi-frames': {
    enabled: false,
    filters: {
      value: [],
      type: 'multi',
      error: false,
      required: true,
      options: [
        'probe',
        'auth',
        'assoc',
        'disassoc',
        'deauth',
        'local-deauth',
        'inactive-deauth',
        'key-mismatch',
        'beacon-report',
        'radar-detected',
      ],
    },
  },
  'dhcp-snooping': {
    enabled: false,
    filters: {
      value: [],
      type: 'multi',
      error: false,
      required: true,
      options: ['ack', 'discover', 'offer', 'request', 'solicit', 'reply', 'renew'],
    },
  },
};

export const SERVICES_FORM = {
  lldp: {
    enabled: false,
    describe: {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    location: {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
  },
  ssh: {
    enabled: false,
    port: {
      value: 22,
      type: 'int',
      error: false,
      required: true,
      maximum: 65535,
    },
    'authorized-keys': {
      value: [],
      type: 'multi-input',
      error: false,
      required: true,
    },
    'password-authentication': {
      type: 'bool',
      value: false,
      error: false,
    },
  },
  ntp: {
    enabled: false,
    servers: {
      value: [],
      type: 'multi-input',
      format: 'uc-host',
      formatExplanation: 'Enter IP or Host Name',
      error: false,
      required: true,
    },
    'local-server': {
      type: 'bool',
      value: false,
      error: false,
    },
  },
  mdns: {
    enabled: false,
    enable: {
      type: 'bool',
      value: false,
      error: false,
    },
  },
  rtty: {
    enabled: false,
    host: {
      type: 'string',
      value: '',
      error: false,
      required: true,
      format: 'uc-host',
    },
    port: {
      value: 5912,
      type: 'int',
      error: false,
      required: true,
      maximum: 65535,
    },
    token: {
      type: 'string',
      value: '',
      error: false,
      required: true,
      maxLength: '32',
      minLength: '32',
    },
  },
  log: {
    enabled: false,
    host: {
      type: 'string',
      value: '',
      error: false,
      required: true,
      format: 'uc-host',
    },
    port: {
      value: 5912,
      type: 'int',
      error: false,
      required: true,
      maximum: 65535,
    },
    proto: {
      value: 'udp',
      type: 'select',
      error: false,
      required: true,
      options: ['udp', 'tcp'],
    },
    size: {
      value: 1000,
      type: 'int',
      error: false,
      required: true,
      minimum: 32,
    },
  },
  http: {
    enabled: false,
    'http-port': {
      value: 80,
      type: 'int',
      error: false,
      required: true,
      maximum: 65535,
      minimum: 1,
    },
  },
  igmp: {
    enabled: false,
    enable: {
      type: 'bool',
      value: false,
      error: false,
    },
  },
  ieee8021x: {
    enabled: false,
    'ca-certificate': {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    'ca-certificate-filename': {
      type: 'string',
      value: '',
      error: false,
      required: false,
    },
    'use-local-certificate': {
      type: 'bool',
      value: false,
      error: false,
    },
    'server-certificate': {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    'server-certificate-filename': {
      type: 'string',
      value: '',
      error: false,
      required: false,
    },
    'private-key': {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    'private-key-filename': {
      type: 'string',
      value: '',
      error: false,
      required: false,
    },
    users: {
      value: [],
      type: 'multi-custom',
      error: false,
      required: true,
    },
  },
  'radius-proxy': {
    enabled: false,
    realms: {
      value: [],
      type: 'multi-custom',
      error: false,
      required: true,
    },
  },
  'online-check': {
    enabled: false,
    'ping-hosts': {
      value: [],
      type: 'multi-input',
      format: 'uc-host',
      formatExplanation: 'Enter IP or Host Name',
      error: false,
      required: true,
    },
    'download-hosts': {
      value: [],
      type: 'multi-input',
      error: false,
      required: true,
    },
    'check-interval': {
      value: 60,
      type: 'int',
      error: false,
      required: true,
      minimum: 0,
      unit: 'seconds',
    },
    'check-threshold': {
      value: 1,
      type: 'int',
      error: false,
      required: true,
      minimum: 0,
    },
    action: {
      value: [],
      type: 'multi',
      error: false,
      required: true,
      options: ['wifi', 'leds'],
    },
  },
  'open-flow': {
    enabled: false,
    controller: {
      type: 'string',
      value: '',
      error: false,
      required: true,
      format: 'cidr',
    },
    mode: {
      value: 'ssl',
      type: 'select',
      error: false,
      required: true,
      options: ['pssl', 'ptcp', 'ssl', 'tcp'],
    },
    'ca-certificate-filename': {
      type: 'string',
      value: '',
      error: false,
      required: false,
    },
    'ca-certificate': {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    'ssl-certificate': {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    'ssl-certificate-filename': {
      type: 'string',
      value: '',
      error: false,
      required: false,
    },
    'private-key': {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    'private-key-filename': {
      type: 'string',
      value: '',
      error: false,
      required: false,
    },
  },
  'data-plane': {
    enabled: false,
    'ingress-filters': {
      value: [],
      type: 'multi-custom',
      error: false,
      required: true,
      structure: {
        name: {
          label: 'name',
          type: 'string',
        },
        program: {
          label: 'program',
          type: 'string',
          format: 'uc-base64',
        },
      },
    },
  },
  'wifi-steering': {
    enabled: false,
    mode: {
      value: 'local',
      type: 'select',
      error: false,
      required: true,
      options: ['local', 'cloud'],
    },
    'assoc-steering': {
      type: 'bool',
      value: false,
      error: false,
    },
    'required-snr': {
      value: 0,
      type: 'int',
      error: false,
      required: true,
      unit: 'db',
    },
    'required-probe-snr': {
      value: 0,
      type: 'int',
      error: false,
      required: true,
      unit: 'db',
    },
    'required-roam-snr': {
      value: 0,
      type: 'int',
      error: false,
      required: true,
      unit: 'db',
    },
    'load-kick-threshold': {
      value: 0,
      type: 'int',
      error: false,
      required: true,
    },
    'auto-channel': {
      type: 'bool',
      value: false,
      error: false,
    },
  },
  'quality-of-service': {
    enabled: false,
    'upload-rate': {
      value: 0,
      type: 'int',
      error: false,
      required: true,
      minimum: 0,
    },
    'download-rate': {
      value: 0,
      type: 'int',
      error: false,
      required: true,
      minimum: 0,
    },
  },
  'facebook-wifi': {
    enabled: false,
    'vendor-id': {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    'gateway-id': {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
    secret: {
      type: 'string',
      value: '',
      error: false,
      required: true,
    },
  },
  'airtime-policies': {
    enabled: false,
    'dns-match': {
      value: [],
      type: 'multi-input',
      error: false,
      required: true,
    },
    'dns-weight': {
      value: 256,
      type: 'int',
      error: false,
      required: true,
      minimum: 0,
    },
  },
};

export const LOCAL_USER_FORM = {
  mac: {
    type: 'string',
    value: '',
    error: false,
    required: true,
    format: 'uc-mac',
  },
  'user-name': {
    type: 'string',
    value: '',
    error: false,
    required: true,
    minLength: 1,
  },
  password: {
    type: 'string',
    value: '',
    error: false,
    required: true,
    minLength: 8,
    maxLength: 63,
  },
  'vlan-id': {
    type: 'int',
    value: '',
    error: false,
    required: true,
    minimum: 0,
    maximum: 4096,
  },
};

export const REALMS_FORM = {
  realm: {
    type: 'string',
    value: '*',
    error: false,
    required: true,
  },
  'auto-discover': {
    type: 'bool',
    value: false,
    error: false,
  },
  host: {
    type: 'string',
    value: '',
    error: false,
    format: 'uc-host',
  },
  port: {
    type: 'int',
    value: 2083,
    error: false,
    required: true,
    minimum: 0,
    maximum: 65535,
  },
  secret: {
    type: 'string',
    value: '',
    error: false,
  },
  'use-local-certificates': {
    type: 'bool',
    value: false,
    error: false,
  },
  'ca-certificate': {
    type: 'string',
    value: '',
    error: false,
  },
  'ca-certificate-filename': {
    type: 'string',
    value: '',
    error: false,
  },
  certificate: {
    type: 'string',
    value: '',
    error: false,
  },
  'certificate-filename': {
    type: 'string',
    value: '',
    error: false,
  },
  'private-key': {
    type: 'string',
    value: '',
    error: false,
  },
  'private-key-filename': {
    type: 'string',
    value: '',
    error: false,
  },
  'private-key-password': {
    type: 'string',
    value: '',
    error: false,
  },
};

export const RADIOS_FORM = {
  band: {
    type: 'select',
    value: '2G',
    error: false,
    required: true,
    options: ['2G', '5G', '5G-lower', '5G-upper', '6G'],
  },
  bandwidth: {
    type: 'select',
    value: 5,
    error: false,
    required: true,
    options: [5, 10, 20],
  },
  channel: {
    type: 'string',
    value: 'auto',
    error: false,
    oneOf: true,
    options: [],
  },
  country: {
    type: 'select',
    value: 'US',
    error: false,
    mergeOptions: true,
    options: [
      { value: 'US', label: 'United States' },
      { value: 'GB', label: 'United Kingdom' },
      { value: 'CA', label: 'Canada' },
      { value: 'AF', label: 'Afghanistan' },
      { value: 'AX', label: 'Aland Islands' },
      { value: 'AL', label: 'Albania' },
      { value: 'DZ', label: 'Algeria' },
      { value: 'AS', label: 'American Samoa' },
      { value: 'AD', label: 'Andorra' },
      { value: 'AO', label: 'Angola' },
      { value: 'AI', label: 'Anguilla' },
      { value: 'AQ', label: 'Antarctica' },
      { value: 'AG', label: 'Antigua And Barbuda' },
      { value: 'AR', label: 'Argentina' },
      { value: 'AM', label: 'Armenia' },
      { value: 'AN', label: 'Netherlands Antilles' },
      { value: 'AW', label: 'Aruba' },
      { value: 'AU', label: 'Australia' },
      { value: 'AT', label: 'Austria' },
      { value: 'AZ', label: 'Azerbaijan' },
      { value: 'BS', label: 'Bahamas' },
      { value: 'BH', label: 'Bahrain' },
      { value: 'BD', label: 'Bangladesh' },
      { value: 'BB', label: 'Barbados' },
      { value: 'BY', label: 'Belarus' },
      { value: 'BE', label: 'Belgium' },
      { value: 'BZ', label: 'Belize' },
      { value: 'BJ', label: 'Benin' },
      { value: 'BM', label: 'Bermuda' },
      { value: 'BT', label: 'Bhutan' },
      { value: 'BO', label: 'Bolivia' },
      { value: 'BA', label: 'Bosnia And Herzegovina' },
      { value: 'BW', label: 'Botswana' },
      { value: 'BV', label: 'Bouvet Island' },
      { value: 'BR', label: 'Brazil' },
      { value: 'IO', label: 'British Indian Ocean Territory' },
      { value: 'BN', label: 'Brunei Darussalam' },
      { value: 'BG', label: 'Bulgaria' },
      { value: 'BF', label: 'Burkina Faso' },
      { value: 'BI', label: 'Burundi' },
      { value: 'KH', label: 'Cambodia' },
      { value: 'CM', label: 'Cameroon' },
      { value: 'CA', label: 'Canada' },
      { value: 'CV', label: 'Cape Verde' },
      { value: 'KY', label: 'Cayman Islands' },
      { value: 'CF', label: 'Central African Republic' },
      { value: 'TD', label: 'Chad' },
      { value: 'CL', label: 'Chile' },
      { value: 'CN', label: 'China' },
      { value: 'CX', label: 'Christmas Island' },
      { value: 'CC', label: 'Cocos (Keeling) Islands' },
      { value: 'CO', label: 'Colombia' },
      { value: 'KM', label: 'Comoros' },
      { value: 'CG', label: 'Congo' },
      { value: 'CD', label: 'Congo, Democratic Republic' },
      { value: 'CK', label: 'Cook Islands' },
      { value: 'CR', label: 'Costa Rica' },
      { value: 'CI', label: "Cote D'Ivoire" },
      { value: 'HR', label: 'Croatia' },
      { value: 'CU', label: 'Cuba' },
      { value: 'CY', label: 'Cyprus' },
      { value: 'CZ', label: 'Czech Republic' },
      { value: 'DK', label: 'Denmark' },
      { value: 'DJ', label: 'Djibouti' },
      { value: 'DM', label: 'Dominica' },
      { value: 'DO', label: 'Dominican Republic' },
      { value: 'EC', label: 'Ecuador' },
      { value: 'EG', label: 'Egypt' },
      { value: 'SV', label: 'El Salvador' },
      { value: 'GQ', label: 'Equatorial Guinea' },
      { value: 'ER', label: 'Eritrea' },
      { value: 'EE', label: 'Estonia' },
      { value: 'ET', label: 'Ethiopia' },
      { value: 'FK', label: 'Falkland Islands (Malvinas)' },
      { value: 'FO', label: 'Faroe Islands' },
      { value: 'FJ', label: 'Fiji' },
      { value: 'FI', label: 'Finland' },
      { value: 'FR', label: 'France' },
      { value: 'GF', label: 'French Guiana' },
      { value: 'PF', label: 'French Polynesia' },
      { value: 'TF', label: 'French Southern Territories' },
      { value: 'GA', label: 'Gabon' },
      { value: 'GM', label: 'Gambia' },
      { value: 'GE', label: 'Georgia' },
      { value: 'DE', label: 'Germany' },
      { value: 'GH', label: 'Ghana' },
      { value: 'GI', label: 'Gibraltar' },
      { value: 'GR', label: 'Greece' },
      { value: 'GL', label: 'Greenland' },
      { value: 'GD', label: 'Grenada' },
      { value: 'GP', label: 'Guadeloupe' },
      { value: 'GU', label: 'Guam' },
      { value: 'GT', label: 'Guatemala' },
      { value: 'GG', label: 'Guernsey' },
      { value: 'GN', label: 'Guinea' },
      { value: 'GW', label: 'Guinea-Bissau' },
      { value: 'GY', label: 'Guyana' },
      { value: 'HT', label: 'Haiti' },
      { value: 'HM', label: 'Heard Island & Mcdonald Islands' },
      { value: 'VA', label: 'Holy See (Vatican City State)' },
      { value: 'HN', label: 'Honduras' },
      { value: 'HK', label: 'Hong Kong' },
      { value: 'HU', label: 'Hungary' },
      { value: 'IS', label: 'Iceland' },
      { value: 'IN', label: 'India' },
      { value: 'ID', label: 'Indonesia' },
      { value: 'IR', label: 'Iran, Islamic Republic Of' },
      { value: 'IQ', label: 'Iraq' },
      { value: 'IE', label: 'Ireland' },
      { value: 'IM', label: 'Isle Of Man' },
      { value: 'IL', label: 'Israel' },
      { value: 'IT', label: 'Italy' },
      { value: 'JM', label: 'Jamaica' },
      { value: 'JP', label: 'Japan' },
      { value: 'JE', label: 'Jersey' },
      { value: 'JO', label: 'Jordan' },
      { value: 'KZ', label: 'Kazakhstan' },
      { value: 'KE', label: 'Kenya' },
      { value: 'KI', label: 'Kiribati' },
      { value: 'KR', label: 'Korea' },
      { value: 'KW', label: 'Kuwait' },
      { value: 'KG', label: 'Kyrgyzstan' },
      { value: 'LA', label: "Lao People's Democratic Republic" },
      { value: 'LV', label: 'Latvia' },
      { value: 'LB', label: 'Lebanon' },
      { value: 'LS', label: 'Lesotho' },
      { value: 'LR', label: 'Liberia' },
      { value: 'LY', label: 'Libyan Arab Jamahiriya' },
      { value: 'LI', label: 'Liechtenstein' },
      { value: 'LT', label: 'Lithuania' },
      { value: 'LU', label: 'Luxembourg' },
      { value: 'MO', label: 'Macao' },
      { value: 'MK', label: 'Macedonia' },
      { value: 'MG', label: 'Madagascar' },
      { value: 'MW', label: 'Malawi' },
      { value: 'MY', label: 'Malaysia' },
      { value: 'MV', label: 'Maldives' },
      { value: 'ML', label: 'Mali' },
      { value: 'MT', label: 'Malta' },
      { value: 'MH', label: 'Marshall Islands' },
      { value: 'MQ', label: 'Martinique' },
      { value: 'MR', label: 'Mauritania' },
      { value: 'MU', label: 'Mauritius' },
      { value: 'YT', label: 'Mayotte' },
      { value: 'MX', label: 'Mexico' },
      { value: 'FM', label: 'Micronesia, Federated States Of' },
      { value: 'MD', label: 'Moldova' },
      { value: 'MC', label: 'Monaco' },
      { value: 'MN', label: 'Mongolia' },
      { value: 'ME', label: 'Montenegro' },
      { value: 'MS', label: 'Montserrat' },
      { value: 'MA', label: 'Morocco' },
      { value: 'MZ', label: 'Mozambique' },
      { value: 'MM', label: 'Myanmar' },
      { value: 'NA', label: 'Namibia' },
      { value: 'NR', label: 'Nauru' },
      { value: 'NP', label: 'Nepal' },
      { value: 'NL', label: 'Netherlands' },
      { value: 'AN', label: 'Netherlands Antilles' },
      { value: 'NC', label: 'New Caledonia' },
      { value: 'NZ', label: 'New Zealand' },
      { value: 'NI', label: 'Nicaragua' },
      { value: 'NE', label: 'Niger' },
      { value: 'NG', label: 'Nigeria' },
      { value: 'NU', label: 'Niue' },
      { value: 'NF', label: 'Norfolk Island' },
      { value: 'MP', label: 'Northern Mariana Islands' },
      { value: 'NO', label: 'Norway' },
      { value: 'OM', label: 'Oman' },
      { value: 'PK', label: 'Pakistan' },
      { value: 'PW', label: 'Palau' },
      { value: 'PS', label: 'Palestinian Territory, Occupied' },
      { value: 'PA', label: 'Panama' },
      { value: 'PG', label: 'Papua New Guinea' },
      { value: 'PY', label: 'Paraguay' },
      { value: 'PE', label: 'Peru' },
      { value: 'PH', label: 'Philippines' },
      { value: 'PN', label: 'Pitcairn' },
      { value: 'PL', label: 'Poland' },
      { value: 'PT', label: 'Portugal' },
      { value: 'PR', label: 'Puerto Rico' },
      { value: 'QA', label: 'Qatar' },
      { value: 'RE', label: 'Reunion' },
      { value: 'RO', label: 'Romania' },
      { value: 'RU', label: 'Russian Federation' },
      { value: 'RW', label: 'Rwanda' },
      { value: 'BL', label: 'Saint Barthelemy' },
      { value: 'SH', label: 'Saint Helena' },
      { value: 'KN', label: 'Saint Kitts And Nevis' },
      { value: 'LC', label: 'Saint Lucia' },
      { value: 'MF', label: 'Saint Martin' },
      { value: 'PM', label: 'Saint Pierre And Miquelon' },
      { value: 'VC', label: 'Saint Vincent And Grenadines' },
      { value: 'WS', label: 'Samoa' },
      { value: 'SM', label: 'San Marino' },
      { value: 'ST', label: 'Sao Tome And Principe' },
      { value: 'SA', label: 'Saudi Arabia' },
      { value: 'SN', label: 'Senegal' },
      { value: 'RS', label: 'Serbia' },
      { value: 'SC', label: 'Seychelles' },
      { value: 'SL', label: 'Sierra Leone' },
      { value: 'SG', label: 'Singapore' },
      { value: 'SK', label: 'Slovakia' },
      { value: 'SI', label: 'Slovenia' },
      { value: 'SB', label: 'Solomon Islands' },
      { value: 'SO', label: 'Somalia' },
      { value: 'ZA', label: 'South Africa' },
      { value: 'GS', label: 'South Georgia And Sandwich Isl.' },
      { value: 'ES', label: 'Spain' },
      { value: 'LK', label: 'Sri Lanka' },
      { value: 'SD', label: 'Sudan' },
      { value: 'SR', label: 'Surilabel' },
      { value: 'SJ', label: 'Svalbard And Jan Mayen' },
      { value: 'SZ', label: 'Swaziland' },
      { value: 'SE', label: 'Sweden' },
      { value: 'CH', label: 'Switzerland' },
      { value: 'SY', label: 'Syrian Arab Republic' },
      { value: 'TW', label: 'Taiwan' },
      { value: 'TJ', label: 'Tajikistan' },
      { value: 'TZ', label: 'Tanzania' },
      { value: 'TH', label: 'Thailand' },
      { value: 'TL', label: 'Timor-Leste' },
      { value: 'TG', label: 'Togo' },
      { value: 'TK', label: 'Tokelau' },
      { value: 'TO', label: 'Tonga' },
      { value: 'TT', label: 'Trinidad And Tobago' },
      { value: 'TN', label: 'Tunisia' },
      { value: 'TR', label: 'Turkey' },
      { value: 'TM', label: 'Turkmenistan' },
      { value: 'TC', label: 'Turks And Caicos Islands' },
      { value: 'TV', label: 'Tuvalu' },
      { value: 'UG', label: 'Uganda' },
      { value: 'UA', label: 'Ukraine' },
      { value: 'AE', label: 'United Arab Emirates' },
      { value: 'GB', label: 'United Kingdom' },
      { value: 'US', label: 'United States' },
      { value: 'UM', label: 'United States Outlying Islands' },
      { value: 'UY', label: 'Uruguay' },
      { value: 'UZ', label: 'Uzbekistan' },
      { value: 'VU', label: 'Vanuatu' },
      { value: 'VE', label: 'Venezuela' },
      { value: 'VN', label: 'Viet Nam' },
      { value: 'VG', label: 'Virgin Islands, British' },
      { value: 'VI', label: 'Virgin Islands, U.S.' },
      { value: 'WF', label: 'Wallis And Futuna' },
      { value: 'EH', label: 'Western Sahara' },
      { value: 'YE', label: 'Yemen' },
      { value: 'ZM', label: 'Zambia' },
      { value: 'ZW', label: 'Zimbabwe' },
    ],
  },
  'channel-mode': {
    type: 'select',
    value: 'HT',
    error: false,
    required: true,
    options: [
      { value: 'HT', label: 'HT (A,B,G,N)' },
      { value: 'VHT', label: 'VHT (A,B,G,N,AC)' },
      { value: 'HE', label: 'HE (WiFi 6,A,B,G,N,AC,AX)' },
    ],
  },
  'channel-width': {
    type: 'select',
    value: 40,
    error: false,
    required: true,
    options: [
      { value: 20, label: '20 MHz' },
      { value: 40, label: '40 MHz' },
      { value: 80, label: '80 MHz' },
      { value: 160, label: '160 MHz' },
    ],
  },
  'require-mode': {
    type: 'select',
    value: '',
    error: false,
    required: false,
    ignoreIfEmpty: true,
    options: [
      { value: '', label: 'None' },
      { value: 'HT', label: 'HT (A,B,G,N)' },
      { value: 'VHT', label: 'VHT (A,B,G,N,AC)' },
      { value: 'HE', label: 'HE (WiFi 6,A,B,G,N,AC,AX)' },
    ],
  },
  mimo: {
    type: 'select',
    value: '',
    error: false,
    required: false,
    ignoreIfEmpty: true,
    options: [
      { value: '', label: 'None' },
      { value: '1x1', label: '1x1' },
      { value: '2x2', label: '2x2' },
      { value: '3x3', label: '3x3' },
      { value: '4x4', label: '4x4' },
      { value: '5x5', label: '5x5' },
      { value: '6x6', label: '6x6' },
      { value: '7x7', label: '7x7' },
      { value: '8x8', label: '8x8' },
    ],
  },
  'tx-power': {
    type: 'int',
    value: 0,
    error: false,
    required: true,
    minimum: 0,
    maximum: 30,
    unit: 'db',
  },
  'legacy-rates': {
    type: 'bool',
    value: false,
    error: false,
  },
  'beacon-interval': {
    type: 'int',
    value: 100,
    error: false,
    required: true,
    minimum: 15,
    maximum: 65535,
    unit: ' ms',
  },
  'dtim-period': {
    type: 'int',
    value: 2,
    error: false,
    required: true,
    minimum: 1,
    maximum: 255,
  },
  'maximum-clients': {
    type: 'int',
    value: '64',
    error: false,
    required: false,
    minimum: 0,
  },
  'hostapd-iface-raw': {
    type: 'multi-custom',
    value: [],
    error: false,
    format: 'url-param',
  },
  rates: {
    enabled: true,
    beacon: {
      type: 'select',
      value: 6000,
      error: false,
      required: false,
      options: [
        { value: 1000, label: '1000' },
        { value: 2000, label: '2000' },
        { value: 5500, label: '5500' },
        { value: 6000, label: '6000' },
        { value: 9000, label: '9000' },
        { value: 11000, label: '11000' },
        { value: 12000, label: '12000' },
        { value: 18000, label: '18000' },
        { value: 24000, label: '24000' },
        { value: 36000, label: '36000' },
        { value: 48000, label: '48000' },
        { value: 54000, label: '54000' },
      ],
    },
    multicast: {
      type: 'select',
      value: 24000,
      error: false,
      required: false,
      options: [
        { value: 1000, label: '1000' },
        { value: 2000, label: '2000' },
        { value: 5500, label: '5500' },
        { value: 6000, label: '6000' },
        { value: 9000, label: '9000' },
        { value: 11000, label: '11000' },
        { value: 12000, label: '12000' },
        { value: 18000, label: '18000' },
        { value: 24000, label: '24000' },
        { value: 36000, label: '36000' },
        { value: 48000, label: '48000' },
        { value: 54000, label: '54000' },
      ],
    },
  },
  he: {
    enabled: false,
    'multiple-bssid': {
      type: 'bool',
      value: false,
      error: false,
    },
    ema: {
      type: 'bool',
      value: false,
      error: false,
    },
    'bss-color': {
      type: 'int',
      value: '64',
      error: false,
      required: false,
      minimum: 0,
    },
  },
};
